# Generated by Django 5.0.4 on 2024-06-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('E', 'Electronics'), ('F', 'Fashion'), ('H', 'Home'), ('T', 'Toys')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='Image URL'),
        ),
    ]
